# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "10-backend-unit: Java Unit tests"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: 'temurin'
          
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: read

    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v4
      with:
         distribution: ${{ inputs.JAVA_DISTRIBUTION }} 
         java-version-file: ./.java-version
         cache: 'maven'
         cache-dependency-path: 'pom.xml' 
  
    - name: Build with Maven
      run: mvn -ntp -B test 
      