name: 16-backend-autoformat.yml
on:
  workflow_call:
    inputs:
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: 'temurin'
    secrets:
      GH_TOKEN:
        required: true
permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Java (version from .java-version file)
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version-file: ./.java-version
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Check formatting with Maven
        id: format-check
        run: |
          mvn -ntp git-code-format:validate-code-format && echo "FORMAT_REQUIRED=false" >> $GITHUB_OUTPUT || echo "FORMAT_REQUIRED=true" >> $GITHUB_OUTPUT

      - name: Run Format if failed
        id: format-step
        if: ${{ steps.format-check.outputs.FORMAT_REQUIRED }} == true  # Only run if the previous step failed
        run: |
          mvn git-code-format:format-code
          CHANGED_FILES=$(git diff --name-only HEAD -- src/)
          CHANGED_FILES_STRING=$(echo "$CHANGED_FILES" | tr '\n' ' ' | sed 's/ $//')
          echo "files=$CHANGED_FILES_STRING" >> $GITHUB_OUTPUT

      - name: Commit changes
        uses: pirafrank/github-commit-sign@v0
        if: ${{ steps.format-check.outputs.FORMAT_REQUIRED }} == true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: "commit --owner=${{ github.repository_owner }} --repo=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --commitMessage='Automatic backend formatting' --changed ${{ steps.format-step.outputs.files }}"
